# Basic Information 
title: Hyelim Lim
position: M.S. Student
affiliation: Hanyang University
affiliation_link: https://www.hanyang.ac.kr
email: yomilimi@hanyang.ac.kr

# Search Engine Optimization (SEO)
keywords: Hyelim Lim
canonical: https://yomilimi.github.io
description: Hyelim Lim's Website

# The option is used to enable the MPI Informatics template.
enable_mpi_logo: false

# The option is used to show the last update time.
enable_last_update: false

# Links
google_scholar: https://scholar.google.co.kr/citations?hl=ko&user=aA1iuUQAAAAJ
cv_link: assets/files/curriculum_vitae.pdf
github_link: https://github.com/yomilimi
linkedin: https://www.linkedin.com/in/hyelim-lim-a072a429a/

# Images 
avatar: ./assets/img/avatar.png
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon.png

# Footnotes
enable_footnote: false

# General Data Protection Regulation (GDPR) information
# If you don't need to add the GDPR information, you may remove the following lines.
imprint: https://imprint.mpi-klsb.mpg.de/inf/people.mpi-inf.mpg.de/username
data_protection: https://data-protection.mpi-klsb.mpg.de/inf/people.mpi-inf.mpg.de/username?lang=en

# The following files will be removed from the generated website.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
